### ISSUE TITLE
Addinh domain

### ISSUE THREAD

**Issue by DedSec002** [ferrolho/instant-popcorn#5]
Hi,

How to host the files like https://ferrolho.github.io/magnet-player/

I own a domain and like to host it on my domain using cpanel?

Any help or suggestions please

**Comment by ferrolho** [comment]
If you are fine having a statically generated website like this, you can host it using [GitHub Pages](https://pages.github.com/).

If you'd like to have your own custom domain name rather than using _github.io_ there is a pretty good guide here: https://help.github.com/articles/using-a-custom-domain-with-github-pages/
